# Generated by Django 5.1.11 on 2026-08-02 12:33

import django.contrib.postgres.indexes
import django.db.models.deletion
import drf_base_app.models.fields
import drf_base_app.models.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    drf_base_app.models.fields.CharField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("name", drf_base_app.models.fields.CharField(max_length=255)),
                ("is_active", drf_base_app.models.fields.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_tenant",
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tenant_id",
                    drf_base_app.models.fields.CharField(db_index=True, max_length=64),
                ),
                ("name", drf_base_app.models.fields.CharField(max_length=255)),
                (
                    "description",
                    drf_base_app.models.fields.TextField(blank=True, default=""),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_workflow",
            },
        ),
        migrations.CreateModel(
            name="WorkflowVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                (
                    "tenant_id",
                    drf_base_app.models.fields.CharField(db_index=True, max_length=64),
                ),
                ("version_number", drf_base_app.models.fields.PositiveIntegerField()),
                (
                    "is_published",
                    drf_base_app.models.fields.BooleanField(default=False),
                ),
                (
                    "published_at",
                    drf_base_app.models.fields.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    drf_base_app.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="rm_workflow.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_workflow_version",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="workflow",
            name="current_version",
            field=drf_base_app.models.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="rm_workflow.workflowversion",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tenant_id",
                    drf_base_app.models.fields.CharField(db_index=True, max_length=64),
                ),
                ("name", drf_base_app.models.fields.CharField(max_length=255)),
                (
                    "description",
                    drf_base_app.models.fields.TextField(blank=True, default=""),
                ),
                ("order", drf_base_app.models.fields.PositiveIntegerField()),
                ("graph", drf_base_app.models.fields.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_version",
                    drf_base_app.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="rm_workflow.workflowversion",
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_stage",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tenant_id",
                    drf_base_app.models.fields.CharField(db_index=True, max_length=64),
                ),
                ("name", drf_base_app.models.fields.CharField(max_length=255)),
                (
                    "description",
                    drf_base_app.models.fields.TextField(blank=True, default=""),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_workspace",
            },
        ),
        migrations.AddField(
            model_name="workflow",
            name="workspace",
            field=drf_base_app.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="rm_workflow.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowversion",
            index=models.Index(
                fields=["tenant_id", "workflow"], name="rm_workflow_tenant__12b907_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowversion",
            constraint=models.UniqueConstraint(
                fields=("workflow", "version_number"),
                name="uniq_workflow_version_number",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=drf_base_app.models.indexes.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["tenant_id", "workflow_version"],
                name="idx_active_tenant_id__a54058db",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["graph"], name="gin_graph_full"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=drf_base_app.models.indexes.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["tenant_id"],
                name="idx_active_tenant_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uniq_workspace_tenant_name_active",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=drf_base_app.models.indexes.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["tenant_id", "workspace"],
                name="idx_active_tenant_id_workspace",
            ),
        ),
    ]
