# Generated by Django 5.1.11 on 2026-08-11 04:54

import drf_base_app.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rm_workflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodetype",
            name="category",
            field=drf_base_app.models.fields.CharField(
                choices=[
                    ("action", "action"),
                    ("condition", "condition"),
                    ("custom", "custom"),
                    ("decision", "decision"),
                    ("input", "input"),
                    ("output", "output"),
                    ("process", "process"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="nodetype",
            name="icon",
            field=drf_base_app.models.fields.CharField(
                choices=[
                    ("ArrowDownToLine", "ArrowDownToLine"),
                    ("ArrowRightLeft", "ArrowRightLeft"),
                    ("ArrowUpFromLine", "ArrowUpFromLine"),
                    ("Clock", "Clock"),
                    ("Cog", "Cog"),
                    ("Filter", "Filter"),
                    ("GitBranch", "GitBranch"),
                    ("Globe", "Globe"),
                    ("Mail", "Mail"),
                    ("Webhook", "Webhook"),
                    ("Workflow", "Workflow"),
                    ("Zap", "Zap"),
                ],
                max_length=100,
            ),
        ),
    ]
