# Generated by Django 5.1.11 on 2026-08-19 10:36

import django.db.models.deletion
import drf_base_app.models.fields
import drf_base_app.models.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_workflow", "0002_alter_nodetype_category_alter_nodetype_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tenant_id",
                    drf_base_app.models.fields.CharField(db_index=True, max_length=64),
                ),
                ("name", drf_base_app.models.fields.CharField(max_length=255)),
                (
                    "description",
                    drf_base_app.models.fields.TextField(blank=True, default=""),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    drf_base_app.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="rm_workflow.workspace",
                        to_field="public_id",
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_project",
            },
        ),
        migrations.AddField(
            model_name="workflow",
            name="project",
            field=drf_base_app.models.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflows",
                to="rm_workflow.project",
                to_field="public_id",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=drf_base_app.models.indexes.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["tenant_id", "workspace"],
                name="idx_project_tenant_ws",
            ),
        ),
    ]
