# Generated by Django 5.1.11 on 2026-08-29 09:17

import drf_base_app.models.fields
import drf_base_app.models.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_workflow", "0003_project_workflow_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="required_form_id",
            field=drf_base_app.models.fields.CharField(
                blank=True, max_length=64, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=drf_base_app.models.indexes.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["tenant_id", "required_form_id"],
                name="idx_active_tenant_id__6179fe9f",
            ),
        ),
    ]
