# Generated by Django 5.1.11 on 2026-09-06 07:46

import django.db.models.deletion
import drf_base_app.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_workflow", "0004_stage_required_form_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompiledVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    drf_base_app.models.fields.CharField(db_index=True, max_length=64),
                ),
                ("runtime_dsl", models.JSONField()),
                (
                    "compiler_version",
                    drf_base_app.models.fields.CharField(max_length=32),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created_by_records",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated_by_records",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_version",
                    drf_base_app.models.fields.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiled_version",
                        to="rm_workflow.workflowversion",
                        to_field="public_id",
                    ),
                ),
            ],
            options={
                "db_table": "rm_workflow_compiled_version",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "workflow_version"],
                        name="rm_workflow_tenant__fe4a58_idx",
                    )
                ],
            },
        ),
    ]
