# Generated by Django 5.1.11 on 2026-09-21 09:27

import drf_base_app.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rm_workflow", "0006_nodetype_execution_strategy_nodetype_output_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="routing_group",
            field=drf_base_app.models.fields.CharField(
                blank=True, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nodetype",
            name="category",
            field=drf_base_app.models.fields.CharField(
                choices=[
                    ("action", "action"),
                    ("control", "control"),
                    ("data", "data"),
                    ("human", "human"),
                    ("trigger", "trigger"),
                    ("workflow", "workflow"),
                ],
                max_length=32,
            ),
        ),
    ]
